
// Generated by https://quicktype.io

export interface CheckTokenResponse {
  id:       string;
  email:    string;
  name:     string;
  lastName: string;
  isActive: boolean;
  roles:    string[];
  token:    string;
}


